#pragma once
#include <stdint.h>

#define SIM_WIDTH 640
#define SIM_HEIGHT 360
#define SIM_PASSES_PER_UPDATE 5u
#define SIM_PIXEL_TYPE_MASK 0xffu
#define SIM_DISSOLVED_SALT_MASK 0x01000000u

typedef enum sim_pixel_type {
  SIM_PIXEL_EMPTY,
  SIM_PIXEL_WOOD,
  SIM_PIXEL_IRON,
  SIM_PIXEL_SAND,
  SIM_PIXEL_RUST,
  SIM_PIXEL_WATER,
  SIM_PIXEL_LAVA,
  SIM_PIXEL_SMOKE,
  SIM_PIXEL_STEAM,
  SIM_PIXEL_ACID,
  SIM_PIXEL_FIRE,
  SIM_PIXEL_OIL,
  SIM_PIXEL_SALT,
  SIM_PIXEL_BEDROCK,
  SIM_PIXEL_TYPE_COUNT
} sim_pixel_type;

